steps:
  # Unit Test
  # - name: 'python:3.9'
  #   id: 'Run Unit Tests'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       python -m unittest discover -s src/unit-test/

  # <if branch == develop end the pipeline>

  # ZIP CF Code
  # - name: 'ubuntu'
  #   id: 'Zip Functions'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       cd src
  #       for dir in get_data_from_bigquery ingest_data_to_bucket process_data_to_bigquery; do
  #         zip -r ${dir}.zip ${dir}/main.py ${dir}/requirements.txt
  #       done
  #   waitFor: ['Run Unit Tests']

  # Upload ZIP files to bucket
  # - name: 'gcr.io/cloud-builders/gsutil'
  #   id: 'Upload Zips'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       gsutil cp src/*.zip gs://function-code-bucket-latam_test/
  #   waitFor: ['Zip Functions']

  #<Terrafom Validate>

  # Terraform Init
  - name: 'hashicorp/terraform:latest'
    id: 'Terraform Init'
    args:
      - 'init'
      - '-input=false'
    dir: 'infra'      


  # Terraform Plan
  - name: 'hashicorp/terraform:latest'
    id: 'Terraform Plan'
    args:
      - 'plan'
      - '-var-file=infra/vars/dev.tfvars'      
      - '-input=false'
      - '-out=tfplan'
    dir: 'infra'      

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET