steps:
  # Paso 1: Ejecutar pruebas unitarias
  - name: 'python:3.9'
    id: 'Run Unit Tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m unittest discover -s src/tests/      

  # Paso 2: Comprimir todas las funciones en archivos .zip
  - name: 'ubuntu'
    id: 'Zip Functions'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd src
        for dir in get_data_from_bigquery ingest_data_to_bucket process_data_to_bigquery; do
          zip -r ${dir}.zip ${dir}/main.py ${dir}/requirements.txt
        done
    waitFor: ['Run Unit Tests']

  # Paso 3: Subir todos los archivos .zip al bucket de Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Upload Zips'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp src/*.zip gs://function-code-bucket-latam_test/
    waitFor: ['Zip Functions']